"""
Transfer (DTO) - 단일 소스

데이터 전달용 BaseModel. State는 워크플로우 상태(TypedDict)용, Transfer는 API/레이어 간 DTO.
Schema 대신 Transfer로 통일.
"""

from .feedback_transfer import (
    FeedbackType,
    FeedbackSeverity,
    FeedbackItemBase,
    FeedbackItemCreate,
    FeedbackItemResponse,
    FeedbackBase,
    FeedbackCreate,
    FeedbackUpdate,
    FeedbackResponse,
    FeedbackListResponse,
    GenerateFeedbackRequest,
    GenerateFeedbackResponse,
    FeedbackReportRequest,
    FeedbackReportResponse,
    FeedbackCorrectionCreate,
    FeedbackCorrectionResponse,
)
from .reference_transfer import (
    IssueBase,
    IssueCreate,
    IssueUpdate,
    IssueResponse,
    ReferenceAnswerBase,
    ReferenceAnswerCreate,
    ReferenceAnswerUpdate,
    ReferenceAnswerResponse,
    ProblemBase,
    ProblemCreate,
    ProblemUpdate,
    ProblemResponse,
    ProblemListResponse,
    IssueExtractionRequest,
    IssueExtractionResponse,
)
from .submission_transfer import (
    SubmissionType,
    SubmissionStatus,
    ParagraphInfo,
    SentenceInfo,
    AnswerStructureResponse,
    UserAnswerBase,
    UserAnswerCreateText,
    UserAnswerCreateImage,
    UserAnswerUpdate,
    UserAnswerResponse,
    UserAnswerListResponse,
    StructureAnalysisRequest,
    StructureAnalysisResponse,
    OCRRequest,
    OCRResponse,
    AnalyzeAndFeedbackResponse,
)
from .reasoning_transfer import (
    TaskType,
    TaskStatus,
    IssueAnalysisResult,
    LogicEvaluationResult,
    ExpressionReviewResult,
    ReasoningResultResponse,
    ReasoningTaskCreate,
    ReasoningTaskUpdate,
    ReasoningTaskResponse,
    ReasoningTaskListResponse,
    IssueAnalysisRequest,
    LogicEvaluationRequest,
    ExpressionReviewRequest,
    ComprehensiveAnalysisRequest,
    AnalysisResponse,
)

__all__ = [
    # Feedback
    "FeedbackType",
    "FeedbackSeverity",
    "FeedbackItemBase",
    "FeedbackItemCreate",
    "FeedbackItemResponse",
    "FeedbackBase",
    "FeedbackCreate",
    "FeedbackUpdate",
    "FeedbackResponse",
    "FeedbackListResponse",
    "GenerateFeedbackRequest",
    "GenerateFeedbackResponse",
    "FeedbackReportRequest",
    "FeedbackReportResponse",
    "FeedbackCorrectionCreate",
    "FeedbackCorrectionResponse",
    # Reference
    "IssueBase",
    "IssueCreate",
    "IssueUpdate",
    "IssueResponse",
    "ReferenceAnswerBase",
    "ReferenceAnswerCreate",
    "ReferenceAnswerUpdate",
    "ReferenceAnswerResponse",
    "ProblemBase",
    "ProblemCreate",
    "ProblemUpdate",
    "ProblemResponse",
    "ProblemListResponse",
    "IssueExtractionRequest",
    "IssueExtractionResponse",
    # Submission
    "SubmissionType",
    "SubmissionStatus",
    "ParagraphInfo",
    "SentenceInfo",
    "AnswerStructureResponse",
    "UserAnswerBase",
    "UserAnswerCreateText",
    "UserAnswerCreateImage",
    "UserAnswerUpdate",
    "UserAnswerResponse",
    "UserAnswerListResponse",
    "StructureAnalysisRequest",
    "StructureAnalysisResponse",
    "OCRRequest",
    "OCRResponse",
    "AnalyzeAndFeedbackResponse",
    # Reasoning
    "TaskType",
    "TaskStatus",
    "IssueAnalysisResult",
    "LogicEvaluationResult",
    "ExpressionReviewResult",
    "ReasoningResultResponse",
    "ReasoningTaskCreate",
    "ReasoningTaskUpdate",
    "ReasoningTaskResponse",
    "ReasoningTaskListResponse",
    "IssueAnalysisRequest",
    "LogicEvaluationRequest",
    "ExpressionReviewRequest",
    "ComprehensiveAnalysisRequest",
    "AnalysisResponse",
]
