"""Initial migration - all domains

Revision ID: a1e0c566a622
Revises:
Create Date: 2026-01-23 17:03:06.648281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1e0c566a622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_enum(name: str, values: list[str]) -> None:
    """Create enum type if not exists (idempotent)."""
    vals = ", ".join(repr(v) for v in values)
    op.execute(
        f"DO $$ BEGIN CREATE TYPE {name} AS ENUM ({vals}); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # Create enums idempotently (skip if already exist)
    _ensure_enum("feedbacktype", ["ISSUE", "LOGIC", "EXPRESSION", "COMPREHENSIVE"])
    _ensure_enum("tasktype", ["ISSUE_ANALYSIS", "LOGIC_EVALUATION", "EXPRESSION_REVIEW", "COMPREHENSIVE"])
    _ensure_enum("taskstatus", ["PENDING", "RUNNING", "COMPLETED", "FAILED"])
    _ensure_enum("submissiontype", ["TEXT", "IMAGE"])
    _ensure_enum("submissionstatus", ["PENDING", "PROCESSING", "COMPLETED", "FAILED"])
    _ensure_enum("feedbackseverity", ["INFO", "SUGGESTION", "WARNING", "CRITICAL"])

    # ### commands auto generated by Alembic - please adjust! ###
    # Use postgresql.ENUM with create_type=False so we don't duplicate enum creation
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_answer_id', sa.String(length=36), nullable=False),
    sa.Column('reasoning_task_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_type', postgresql.ENUM('ISSUE', 'LOGIC', 'EXPRESSION', 'COMPREHENSIVE', name='feedbacktype', create_type=False), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_user_answer_id'), 'feedbacks', ['user_answer_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reasoning_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_results_task_id'), 'reasoning_results', ['task_id'], unique=False)
    op.create_table('reasoning_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', postgresql.ENUM('ISSUE_ANALYSIS', 'LOGIC_EVALUATION', 'EXPRESSION_REVIEW', 'COMPREHENSIVE', name='tasktype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus', create_type=False), nullable=False),
    sa.Column('user_answer_id', sa.String(length=36), nullable=False),
    sa.Column('reference_answer_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('source_domain', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('submission_type', postgresql.ENUM('TEXT', 'IMAGE', name='submissiontype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus', create_type=False), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('processed_content', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_answer_id', sa.String(length=36), nullable=False),
    sa.Column('paragraphs', sa.JSON(), nullable=True),
    sa.Column('sentences', sa.JSON(), nullable=True),
    sa.Column('paragraph_count', sa.JSON(), nullable=True),
    sa.Column('sentence_count', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_answer_id'], ['user_answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_answer_id')
    )
    op.create_table('feedback_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'SUGGESTION', 'WARNING', 'CRITICAL', name='feedbackseverity', create_type=False), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_items_feedback_id'), 'feedback_items', ['feedback_id'], unique=False)
    op.create_table('reference_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference_answer_id', sa.String(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('related_cases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reference_answer_id'], ['reference_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop login_logs only if it exists (legacy table from another context)
    op.execute("DROP TABLE IF EXISTS login_logs CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='login_logs_pkey')
    )
    op.create_index('idx_user_id', 'login_logs', ['user_id'], unique=False)
    op.create_index('idx_provider', 'login_logs', ['provider'], unique=False)
    op.create_index('idx_login_time', 'login_logs', [sa.text('login_time DESC')], unique=False)
    op.create_index('idx_created_at', 'login_logs', [sa.text('created_at DESC')], unique=False)
    op.drop_table('issues')
    op.drop_table('reference_answers')
    op.drop_index(op.f('ix_feedback_items_feedback_id'), table_name='feedback_items')
    op.drop_table('feedback_items')
    op.drop_table('answer_structures')
    op.drop_table('user_answers')
    op.drop_table('reasoning_tasks')
    op.drop_index(op.f('ix_reasoning_results_task_id'), table_name='reasoning_results')
    op.drop_table('reasoning_results')
    op.drop_table('problems')
    op.drop_index(op.f('ix_feedbacks_user_answer_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
