"""Add training domain tables

Revision ID: deaccc34e525
Revises: e33aa43c4583
Create Date: 2026-01-26 15:07:13.546065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deaccc34e525'
down_revision: Union[str, Sequence[str], None] = 'e33aa43c4583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum 타입 생성 (이미 존재하면 스킵)
    from sqlalchemy.dialects.postgresql import ENUM
    from sqlalchemy import text, inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    # Enum 타입 존재 여부 확인 함수
    def enum_exists(enum_name: str) -> bool:
        """Enum 타입이 이미 존재하는지 확인"""
        result = conn.execute(text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """), {"enum_name": enum_name})
        return result.scalar()

    # 테이블 존재 여부 확인 함수
    def table_exists(table_name: str) -> bool:
        """테이블이 이미 존재하는지 확인"""
        result = conn.execute(text("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = :table_name
            )
        """), {"table_name": table_name})
        return result.scalar()

    # TrainingDataStatus enum
    if not enum_exists('trainingdatastatus'):
        training_data_status_enum = ENUM('PENDING', 'PROCESSED', 'USED', name='trainingdatastatus', create_type=True)
        training_data_status_enum.create(conn)

    # TrainingJobStatus enum
    if not enum_exists('trainingjobstatus'):
        training_job_status_enum = ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='trainingjobstatus', create_type=True)
        training_job_status_enum.create(conn)

    # ModelVersionStatus enum
    if not enum_exists('modelversionstatus'):
        model_version_status_enum = ENUM('TRAINING', 'ACTIVE', 'ARCHIVED', 'DEPRECATED', name='modelversionstatus', create_type=True)
        model_version_status_enum.create(conn)

    # 순환 참조 해결: 먼저 model_versions를 FK 없이 생성
    # 테이블이 이미 존재하면 스킵
    if not table_exists('model_versions'):
        # ENUM 타입이 이미 존재할 수 있으므로 직접 PostgreSQL 타입 사용
        op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('training_job_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),  # 임시로 String 사용
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('test_metrics', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('data_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )

    if not table_exists('training_data'):
        op.create_table('training_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=True),
    sa.Column('reference_answer_id', sa.String(length=36), nullable=True),
    sa.Column('user_answer_id', sa.String(length=36), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('reference_answer_text', sa.Text(), nullable=False),
    sa.Column('user_answer_text', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),  # 임시로 String 사용
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    if not table_exists('training_jobs'):
        op.create_table('training_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),  # 임시로 String 사용
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('training_data_ids', sa.JSON(), nullable=True),
    sa.Column('train_size', sa.Integer(), nullable=True),
    sa.Column('val_size', sa.Integer(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('loss_history', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Foreign key constraints 추가 (순환 참조 해결, 이미 존재하면 스킵)
    # Foreign Key 존재 여부 확인 함수
    def fk_exists(fk_name: str) -> bool:
        """Foreign Key가 이미 존재하는지 확인"""
        result = conn.execute(text("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_schema = 'public'
                AND constraint_name = :fk_name
                AND constraint_type = 'FOREIGN KEY'
            )
        """), {"fk_name": fk_name})
        return result.scalar()

    if not fk_exists('fk_training_jobs_model_version'):
        op.create_foreign_key('fk_training_jobs_model_version', 'training_jobs', 'model_versions', ['model_version_id'], ['id'])
    if not fk_exists('fk_model_versions_training_job'):
        op.create_foreign_key('fk_model_versions_training_job', 'model_versions', 'training_jobs', ['training_job_id'], ['id'])

    # ENUM 타입으로 변경 (이미 존재하는 타입 사용, 테이블이 존재하고 컬럼이 String 타입일 때만)
    if table_exists('model_versions') and enum_exists('modelversionstatus'):
        # 컬럼 타입 확인
        col_type_result = conn.execute(text("""
            SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public'
            AND table_name = 'model_versions'
            AND column_name = 'status'
        """))
        col_type = col_type_result.scalar() if col_type_result else None
        if col_type == 'character varying':
            op.execute("ALTER TABLE model_versions ALTER COLUMN status TYPE modelversionstatus USING status::modelversionstatus")

    if table_exists('training_data') and enum_exists('trainingdatastatus'):
        col_type_result = conn.execute(text("""
            SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public'
            AND table_name = 'training_data'
            AND column_name = 'status'
        """))
        col_type = col_type_result.scalar() if col_type_result else None
        if col_type == 'character varying':
            op.execute("ALTER TABLE training_data ALTER COLUMN status TYPE trainingdatastatus USING status::trainingdatastatus")

    if table_exists('training_jobs') and enum_exists('trainingjobstatus'):
        col_type_result = conn.execute(text("""
            SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public'
            AND table_name = 'training_jobs'
            AND column_name = 'status'
        """))
        col_type = col_type_result.scalar() if col_type_result else None
        if col_type == 'character varying':
            op.execute("ALTER TABLE training_jobs ALTER COLUMN status TYPE trainingjobstatus USING status::trainingjobstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_jobs')
    op.drop_table('training_data')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
